version: "3.9"

services:
  postgres:
    image: postgres:18-alpine
    container_name: traveler_db
    restart: unless-stopped

    env_file:
      - .env

    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    command:
      - postgres
      - -c
      - listen_addresses=*
      - -c
      - wal_level=logical
      - -c
      - max_replication_slots=10
      - -c
      - max_wal_senders=10
      - -c
      - max_logical_replication_workers=4
      - -c
      - max_worker_processes=10

    ports:
      - "5432:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/migrations:/docker-entrypoint-migrations:ro
      - ./db/replications/common:/docker-entrypoint-initdb.d:ro
      - ./db/replications/publisher:/docker-entrypoint-replications:ro

    networks:
      - traveler_network

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s


  postgres_sub:
    image: postgres:18-alpine
    container_name: traveler_db_replica
    restart: unless-stopped

    env_file:
      - .env

    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    command:
      - postgres
      - -c
      - listen_addresses=*
      - -c
      - wal_level=logical

    depends_on:
      postgres:
        condition: service_healthy

    ports:
      - "55432:5432"

    volumes:
      - pgdata_replica:/var/lib/postgresql/data
      - ./db/replications/common:/docker-entrypoint-initdb.d:ro
      - ./db/replications/subscriber:/docker-entrypoint-replications:ro

    networks:
      - traveler_network


  postgres_sub2:
    image: postgres:18-alpine
    container_name: traveler_db_replica2
    restart: unless-stopped

    env_file:
      - .env

    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    command:
      - postgres
      - -c
      - listen_addresses=*
      - -c
      - wal_level=logical

    depends_on:
      postgres:
        condition: service_healthy

    ports:
      - "55433:5432"

    volumes:
      - pgdata_replica2:/var/lib/postgresql/data
      - ./db/replications/common:/docker-entrypoint-initdb.d:ro
      - ./db/replications/subscriber:/docker-entrypoint-replications:ro

    networks:
      - traveler_network


  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: traveler_app
    restart: unless-stopped

    env_file:
      - .env

    depends_on:
      postgres:
        condition: service_healthy

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SERVER_PORT: ${APP_PORT}

    ports:
      - "${APP_PORT}:${APP_PORT}"

    networks:
      - traveler_network


volumes:
  pgdata:
  pgdata_replica:
  pgdata_replica2:

networks:
  traveler_network:
    driver: bridge
