version: "3.9"

services:
  postgres:
    image: postgres:18-alpine
    container_name: traveler_db
    restart: unless-stopped

    env_file:
      - .env

    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    command:
      - postgres
      - -c
      - listen_addresses=*
      - -c
      - wal_level=logical
      - -c
      - max_wal_senders=10
      - -c
      - max_replication_slots=10

    ports:
      - "5432:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data

    networks:
      - traveler_network

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres_physical:
    image: postgres:18-alpine
    container_name: traveler_db_physical
    environment:
      PGPASSWORD: replicator_pass
      PGDATA: /var/lib/postgresql/data
    entrypoint:
      - /bin/sh
      - -c
      - |
        echo "Fixing permissions..."
        chown -R postgres:postgres /var/lib/postgresql/data
        
        echo "Waiting for primary..."
        until pg_isready -h traveler_db -p 5432; do
          sleep 2
        done
        
        echo "Cleaning data directory..."
        rm -rf /var/lib/postgresql/data/*
        
        echo "Running base backup..."
        su postgres -c "
          pg_basebackup \
            -h traveler_db \
            -p 5432 \
            -U replicator \
            -D /var/lib/postgresql/data \
            -Fp -Xs -P -R
        "
        
        echo "Starting postgres..."
        exec su postgres -c 'postgres -D /var/lib/postgresql/data'
    volumes:
      - pgdata_physical:/var/lib/postgresql/data
    networks:
      - traveler_network



  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: traveler_app
    restart: unless-stopped

    env_file:
      - .env

    depends_on:
      postgres:
        condition: service_healthy

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}

    ports:
      - "${APP_PORT}:${APP_PORT}"

    networks:
      - traveler_network


volumes:
  pgdata:
  pgdata_physical:

networks:
  traveler_network:
    driver: bridge
